# action.yml
name: "yamlfix"
description: "Check, lint and fix YAML files"
author: "Davi Mello"

branding:
  color: "blue"
  icon: "check-circle"

inputs:
  file_path:
    description: "The file or directory to check"
    required: false
    default: "."

  args:
    description: "Arguments to pass to the command"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"

  args:
    - ${{ inputs.args }}
    - ${{ inputs.file_path }}
